//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO.Hue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SILO.Hue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C8E2F1,D7E5EC,E8F6FF,E0EEFD,E8F6FF,C3D6ED.
        /// </summary>
        internal static string concentrate {
            get {
                return ResourceManager.GetString("concentrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1D4C9C,547BB4,A2B7D6,E8EFF7,7392C0,D6E0EC,124296,BDCCE3,7695C3.
        /// </summary>
        internal static string energize {
            get {
                return ResourceManager.GetString("energize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0000,FFA500,FFFF00,00FF00,0000FF,800080.
        /// </summary>
        internal static string rainbow {
            get {
                return ResourceManager.GetString("rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E39C3D,E7A958,EFC690,F5DBB9,F9EBD9,E39C3E,FDF7F0,EEC48B,FEFBF8,FBF0E3.
        /// </summary>
        internal static string reading {
            get {
                return ResourceManager.GetString("reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD982A,E7BA27,EFD327,DD982A,EAC227,F9EF29,DD9C29,EECD27.
        /// </summary>
        internal static string relax {
            get {
                return ResourceManager.GetString("relax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F0F0F8,11294F,5C93D6,A4C4F7,3D4E79,E0E3F4,75ABE7,D1D9EE.
        /// </summary>
        internal static string snow {
            get {
                return ResourceManager.GetString("snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 922C16,D6682B,D56E29,E1BA53,B9491B,751A69,751A69,8A1A66.
        /// </summary>
        internal static string sunset {
            get {
                return ResourceManager.GetString("sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 033345,3959C4,13A1BB,9D343C,05456B,D87B7B,09213A,08B2D3,076FA4.
        /// </summary>
        internal static string underwater {
            get {
                return ResourceManager.GetString("underwater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FE8B14,C51E0C,E42500,F6F042,E50100,FB1218,DB5D06.
        /// </summary>
        internal static string volcano {
            get {
                return ResourceManager.GetString("volcano", resourceCulture);
            }
        }
    }
}
