//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILO.Hue {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class HueSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static HueSettings defaultInstance = ((HueSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HueSettings())));
        
        public static HueSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pmtest1pmtest1")]
        public string HueApiKey {
            get {
                return ((string)(this["HueApiKey"]));
            }
            set {
                this["HueApiKey"] = value;
            }
        }
    }
}
